# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 785efde92143e97c0a3ebcf25c859c703bf4f8dc7d9e9714eb8f33afbbcb74a4a10afac2646efc69d8ca61ef9c67df91f90716cf10eb5450dd156851d919f229

test:
  secret_key_base: 57cb43077ff7c9537b154457a26863548eeb3f2e487ab7a061e0ea511163b7143f633aace2d3a0988ad54bc8829553b02d77ebe3cf31170266a5ede358be6439

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
